# Generated by Django 3.1 on 2020-08-30 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('head', models.CharField(max_length=64)),
                ('stuff', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_task', to='projects.department'),
        ),
        migrations.AlterField(
            model_name='task',
            name='starting_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_at_hand', to='projects.department'),
        ),
    ]
