# Generated by Django 3.1 on 2020-08-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200830_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=24)),
                ('l_name', models.CharField(max_length=24)),
                ('task', models.ManyToManyField(blank=True, related_name='member', to='projects.Task')),
            ],
        ),
    ]
