# Generated by Django 3.1 on 2020-08-30 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_teammembers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMembers',
            new_name='TeamMember',
        ),
    ]
