# Generated by Django 3.1 on 2020-09-11 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200830_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='satisfaction_rate',
            new_name='days_to_complete',
        ),
    ]
