# Generated by Django 3.1 on 2020-09-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200911_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name_task',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
