# Generated by Django 3.1 on 2020-09-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_task_name_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name_task',
            field=models.CharField(blank=True, max_length=265),
        ),
    ]
